---
title: "Instructions for students"
output: rmarkdown::html_vignette
author:
date:
vignette: >
  %\VignetteIndexEntry{Course management with ghclass}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
params:
  course: Course name
  org: GitHub organization
---

<style type="text/css">

h1.title {
  font-size: 38px;
  color: #581845;
}
h1 { /* Header 1 */
  font-size: 26px;
  color: #581845;
}
h2 { /* Header 2 */
    font-size: 20px;
  color: #900C3F;
}
h3 { /* Header 3 */
  font-size: 14px;
  color: #C70039;
}
</style>

Welcome to ``r params$course``! This course uses GitHub to turn in and view feedback on your assignments. You will have the opportunity to give and receive feedback on your peers' work. Please read the instructions below.

## Creating a GitHub account
If you do not have one already, please create a free [GitHub account](https://github.com). When you created the account, please enter your user name on the list provided by the instructor of this course.

## Accept invitation to class organization
Your instructor will add you to the ``r params$org`` organization on Github. Once you are added, you will receive an invitation to join to the email address you specified when creating your GitHub account. Please accept the invitation to join the ``r params$org`` organization.

## Assignment
Your instructor will create a personal repository for your assignment. It might be called something like ``r paste0(params$org, "/hw1-username")``. Please complete the following steps:

1. Clone the assignment repository to a local repository
2. Complete the assignment
3. Push the completed assignment to your remote repository before the posted deadline

<span style="color:#C70039">**Things to keep in mind**</span>

- <span style="color:#C70039">Save in repository:</span> Please save your work only in the assignment-specific repository created for you by the instructor. The files will automatically be moved to your peer reviewers. If you save files outside this repository, your work may not be submitted for review and grading.
- <span style="color:#C70039">Do not change file names:</span> Please do not change the file names of files in your repository. 

## Review
Once the assignment is complete, the review process begins. Your instructor will create a second repository for you, names something like ``r paste0(params$org, "/hw1-review-username")``. The new repository contains folders for each of your peers' assignments you are asked to review. Each folder will also contain a review form for you to fill out. 

You instructor will open an issue in this new repository with a check list of tasks to complete. You will go through the following steps:

1. Clone the review repository to a local repository
2. Review and give comments on the assignment of each of your peers
3. Fill out review form
4. Push the changes to your remote repository before the posted deadline

### Review assignment
When reviewing your peers' work, please give them helpful comments and suggestions directly in their assignment file.

### Fill out review form
The review form is a RMarkdown (`.Rmd`) document that contains questions for you to answer for each of your classmates' assignments you reviewer. It also contains a co-called [YAML header](https://bookdown.org/yihui/rmarkdown/html-document.html). The YAML header might look like this:

```
---
title: "Reviewer feedback form"
output: github_document
params:
  q1_score: NA
  q2_score: NA
---
```
You will see empty parameters (or placeholders) in the `params` section of the YAML, here they are called `q1_score` and `q2_score`. Please replace the NA for each of the paramters with the number of points you  given the author for each question. A completed YAML header will look like this:
```
---
title: "Reviewer feedback form"
output: github_document
params:
  q1_score: 3
  q2_score: 0
---
```

## Engage with feedback feedback
Once the review process is complete, your instructor will pass the feedback that your peers gave on your assignment back to you. Each reviewer's feedback is contained in a separate folder, for example called `rev1` for reviewer 1's feeback, `rev2` for reviewer 2's feedback, and so on. Please read their commments carefully and make necessary changes to your assignment. 

1. Pull the changes on your remote assignment repository into your local copy of the assignment repository
2. Review changes suggested by the reviewers on your assignment and make necessary changes. 
3. If instructed by the instructor, fill out the rating form on the feedback you received
4. Push the changes to your remote repository before the posted deadline

You instructor will open an issue in your assignment repository with a check list of tasks to complete. 

### Fill out rating form
The reviewer folders that were created contain a RMarkdown document with a short questionnaire asking you to rate the feedback you received from your peers. Again, please enter your score for each category in the YAML header of the form, replacing the NAs. A completed form might look like this.
```
---
title: "Author feedback form"
output: github_document
params:
  helpfulness: 3
  accuracy: 2
  fairness: 4
---
```


