cli_glue = function(..., .envir = parent.frame()) {
  cli::cli_format_method(cli::cli_text(..., .envir = .envir))
}

empty_result = function(res) {
  if (is_safely_result(res)){
    empty_result(result(res))
  } else {
    (length(res) == 1 & all(res == "")) | (is.list(res) & length(res) == 0)
  }
}


is_safely_result = function(x) {
  if (!is.list(x))
    return(FALSE)

  if (!all(c("result", "error") %in% names(x)))
    return(FALSE)

  TRUE
}

check_safely_result = function(x) {
  if (!is_safely_result(x))
    stop(cli_glue("Object is not a {.code purrr::safely} result"), call. = FALSE)
}

result = function(x) {
  #check_safely_result(x)
  x[["result"]]
}

error = function(x) {
  #check_safely_result(x)
  x[["error"]]
}

succeeded = function(x) {
  !is.null(result(x))
}

failed = function(x) {
  !is.null(error(x))
}

any_failed = function(x) {
  any(purrr::map_lgl(x, failed))
}

return_on_any_failed = function(x) {
  if (any_failed(x))
    do.call(return, list(), envir = sys.frame(-1))
}


error_msg = function(x, wrap = 80, prefix = "\u2514\u2500 ") {

  wrap = min(wrap, getOption("width"))

  err = sub("\\n.*", "", error(x)[["message"]])

  # These are specific to the errors generated by gh
  msg = error(x)[["content"]][["message"]]
  doc = error(x)[["content"]][["documentation_url"]]

  if (!is.null(doc))
    doc = paste0("(See ", doc, ")")

  if (!is.null(msg)) {
    msg = paste(msg, doc)
    msg = trimws(msg)
    msg = strwrap(msg, width=wrap, initial = prefix, exdent=nchar(prefix))
    msg = paste(msg, collapse = "\n")
    err = paste(err, msg, sep="\n")
  }

  err
}


allow_error = function(res, message = NULL, class = NULL, result = "") {

  stopifnot(!is.null(message) | !is.null(class))

  if (succeeded(res))
    return(res)

  message_flag = TRUE
  if (!is.null(message)) {
    message_flag = grepl(message, error_msg(res))
  }

  class_flag = TRUE
  if (!is.null(class)) {
    class_flag = inherits(error(res), class)
  }

  if (message_flag & class_flag) {
    list(
      result = result,
      error = NULL
    )
  } else {
    res
  }
}

ternary = function(check, success, fail) {
  if (check)
    success
  else
    fail
}

# TODO - fix error_msg processing - doesnt work for PR and some others

status_msg = function(x, success = NULL, fail = NULL, include_error_msg = FALSE, .envir = parent.frame()) {


  if (succeeded(x) & !is.null(success)) {
    cli::cli_alert_success(success, wrap = TRUE, .envir = .envir)
  }

  if (failed(x) & !is.null(fail)) {
    cli::cli_alert_danger(fail, wrap = TRUE, .envir = .envir)
    if (include_error_msg) {
      cli::cli_div(theme = list(ul = list("list-style-type" = "└─", "padding-left" = 0)))
      cli::cli_ul(error_msg(x))
    }
  }
}


